// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Name } from "./Name";

export interface Person { id: string, title: string, name: Name, marketing: boolean, }