// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Name } from "./Name";

export interface PersonForCreate { title: string, name: Name, marketing?: boolean, }